version: '3.8'

services:
  homedecide:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homedecide-app
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./utils:/app/utils
    environment:
      - STREAMLIT_SERVER_MAX_UPLOAD_SIZE=50
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s